### ISSUE TITLE
Item Navigation

### ISSUE THREAD

**Issue by michielbaird** [DEADBEEF/translate#2]
So we basically need to hook into the data now. Once we have this navigation interface we can start adding user tools and hooking that into a database.

**Comment by zuch** [comment]
The parser.py (https://github.com/DEADBEEF/translate/blob/Sascha/translator/main/parser.py) in Sascha branch is able to return an array of objects that have (path, depth, directory folders and directory files). 

You guys can go ahead using parser.py while I work on the drop-down menu, been busy all day with EC.

**Comment by michielbaird** [comment]
Ill probably merge my changes later tonight. Could we have a small design talk tomorrow? Just so we know where we are headed and how these components are going to end up working?
